/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DBFormDriver.java
 *
 * Created on Apr 19, 2010, 2:06:36 PM
 */

package ext.drivers;

import ext.java.sql.MyDerbyConnectionManager;
import ext.java.sql.MySQLConnectionManager;
import ext.javax.swing.db.DBCheckBox;
import ext.javax.swing.db.DBForm;
import ext.javax.swing.db.DBTextField;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Menachem
 */
public class DBFormDriver extends javax.swing.JFrame {

    /** Creates new form DBFormDriver */
    public DBFormDriver() {
        initComponents();
        initMyComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    dbf = new ext.javax.swing.db.DBForm();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().add(dbf, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new DBFormDriver().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private ext.javax.swing.db.DBForm dbf;
  // End of variables declaration//GEN-END:variables
  private void initMyComponents() {
    try {
      conn = new MySQLConnectionManager("password", "testDB1").getConnection();
      dbf.setConnection(conn);
      dbf.setRecordSource("TABLE1");
//      dbf.setFilter("table = 1");
    } catch (SQLException e) {e.printStackTrace();}
    
     DBTextField dbtf  = new DBTextField("FIRST_NAME");
     dbtf.setVisible(true);
    dbtf.setPreferredSize(new Dimension(75, 20));
    		dbtf.setDefaultValue("Smith");

    dbf.getContentPane().add(dbtf);    
   
    dbtf  = new DBTextField("LAST_NAME");

//		dbtf  = new DBTextField("[FIRST_NAME] + [LAST_NAME]");
    dbtf.setPreferredSize(new Dimension(75, 20));
    dbf.add(dbtf);
    
		dbtf  = new DBTextField("ID");
		dbtf.setPreferredSize(new Dimension(75, 20));
    dbf.add(dbtf);  
    
    DBCheckBox dbcb = new DBCheckBox("FAT");
    dbcb.setDefaultValue(true);
    dbf.add(dbcb);
    
//		dbtf = new DBTextField("[first_name] + \" \" + [last_name]");
//		dbtf.setPreferredSize(new Dimension(75, 20));
//    dbf.add(dbtf);
//		System.out.println(dbtf.getFieldName());
   
    pack();

  }
  Connection conn;

}
