/*
 * ContinuousFormEvent.java
 *
 * Created on March 5, 2008, 12:32 PM
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package jentry.sql.events;

import jentry.sql.swing.DBContinuousForm;
import jentry.sql.swing.DBContinuousForm.Subform;
import java.util.EventObject;

/**
 * A ContinuousFormEvent event is generated by a DBContinuousForm each time a
 * Subform is added or removed
 *
 * @author Menachem & Shira
 */
public class ContinuousFormEvent extends EventObject {
  
  /** Creates a new instance of ContinuousFormEvent */
  public ContinuousFormEvent(DBContinuousForm source) {
    this(source, null);
  }
  public ContinuousFormEvent(DBContinuousForm source, Subform subform) {
    super(source);
    setSubform(subform);
  }
  
  
  public DBContinuousForm getSource() {return (DBContinuousForm) super.getSource();}
  
  public Subform getSubform() {return subform;}
  public void setSubform(Subform subform) {this.subform = subform;}
  
  protected Subform subform = null;
}
